server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_snob
    username: user1
    password: 123
    hikari:
      driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml